// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Secure HttpOnly cookie-based configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use HttpOnly cookies but allow session persistence for OAuth
    persistSession: true, // Required for OAuth callbacks
    autoRefreshToken: true, // Let server handle refresh via HttpOnly cookies
    detectSessionInUrl: true, // Handle OAuth callbacks
    flowType: 'pkce', // Use PKCE for better security
  }
});