// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Standard Supabase configuration with localStorage persistence
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // Keep session in localStorage
    autoRefreshToken: true, // Auto refresh tokens
    detectSessionInUrl: true, // Handle OAuth callbacks
    flowType: 'pkce', // Use PKCE for better security
    storage: window.localStorage, // Explicitly use localStorage
    storageKey: 'sb-auth-token' // Standard Supabase storage key
  }
});